import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        "background-secondary": "var(--background-secondary)",
        "background-tertiary": "var(--background-tertiary)",
        foreground: "var(--foreground)",
        "foreground-secondary": "var(--foreground-secondary)",
        "foreground-tertiary": "var(--foreground-tertiary)",
        spark: {
          pink: "#ff007f",
          "pink-light": "#ff3ea5",
          purple: "#7c3aed",
          "purple-light": "#a855f7",
          cyan: "#06f7ff",
          "cyan-light": "#67f8ff",
          blue: "#3b82f6",
          "blue-light": "#60a5fa",
          amber: "#f59e0b",
          rose: "#f43f5e",
          emerald: "#10b981",
        },
        glass: {
          DEFAULT: "rgba(255, 255, 255, 0.03)",
          border: "rgba(255, 255, 255, 0.06)",
          hover: "rgba(255, 255, 255, 0.08)",
          strong: "rgba(255, 255, 255, 0.08)",
          active: "rgba(255, 255, 255, 0.12)",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        display: ["Inter", "system-ui", "-apple-system", "sans-serif"],
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
        "4xl": "var(--radius-4xl)",
        full: "var(--radius-full)",
      },
      animation: {
        float: "float 8s ease-in-out infinite",
        "float-delayed": "float-delayed 10s ease-in-out infinite",
        "float-soft": "float-soft 6s ease-in-out infinite",
        "fade-in": "fadeIn 0.5s var(--ease-spring) forwards",
        "fade-in-up": "fadeInUp 0.6s var(--ease-spring) forwards",
        "fade-in-down": "fadeInDown 0.6s var(--ease-spring) forwards",
        "fade-in-left": "fadeInLeft 0.5s var(--ease-spring) forwards",
        "fade-in-right": "fadeInRight 0.5s var(--ease-spring) forwards",
        "fade-in-scale": "fadeInScale 0.5s var(--ease-spring) forwards",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        aurora: "aurora 8s ease-in-out infinite alternate",
        "aurora-2": "aurora2 10s ease-in-out infinite alternate",
        "spin-slow": "spin-slow 20s linear infinite",
        "spin-slower": "spin-slower 30s linear infinite",
        "bounce-gentle": "bounce-gentle 2s ease-in-out infinite",
        "slide-up": "slideUp 0.8s var(--ease-spring) forwards",
        "slide-down": "slideDown 0.8s var(--ease-spring) forwards",
        "scale-in": "scaleIn 0.4s var(--ease-spring) forwards",
        shimmer: "shimmer 3s ease-in-out infinite",
        "gradient-shift": "gradient-shift 8s ease infinite",
        morph: "morph 8s ease-in-out infinite",
        "text-reveal": "text-reveal 1.2s var(--ease-spring) forwards",
        heartbeat: "heartbeat 1.5s ease-in-out infinite",
        "notification-in": "notification-slide-in 0.4s var(--ease-spring) forwards",
        "notification-out": "notification-slide-out 0.4s var(--ease-spring) forwards",
        orb: "orb-move 15s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "25%": { transform: "translateY(-12px) rotate(0.5deg)" },
          "75%": { transform: "translateY(6px) rotate(-0.3deg)" },
        },
        "float-delayed": {
          "0%, 100%": { transform: "translateY(0px)" },
          "33%": { transform: "translateY(-16px)" },
          "66%": { transform: "translateY(8px)" },
        },
        "float-soft": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        fadeInUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeInDown: {
          from: { opacity: "0", transform: "translateY(-20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeInLeft: {
          from: { opacity: "0", transform: "translateX(-20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        fadeInRight: {
          from: { opacity: "0", transform: "translateX(20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        fadeInScale: {
          from: { opacity: "0", transform: "scale(0.96)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        pulseGlow: {
          "0%, 100%": { opacity: "0.4", transform: "scale(1)" },
          "50%": { opacity: "0.8", transform: "scale(1.05)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "0.6" },
          "50%": { opacity: "1" },
        },
        aurora: {
          "0%": { transform: "translateX(-50%) translateY(-50%) rotate(0deg) scale(1)" },
          "50%": { transform: "translateX(50%) translateY(30%) rotate(180deg) scale(1.2)" },
          "100%": { transform: "translateX(-30%) translateY(-20%) rotate(360deg) scale(0.9)" },
        },
        aurora2: {
          "0%": { transform: "translateX(50%) translateY(50%) rotate(0deg) scale(1.1)" },
          "50%": { transform: "translateX(-40%) translateY(-30%) rotate(-180deg) scale(0.8)" },
          "100%": { transform: "translateX(30%) translateY(40%) rotate(-360deg) scale(1.3)" },
        },
        "bounce-gentle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(60px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          from: { opacity: "0", transform: "translateY(-60px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          from: { opacity: "0", transform: "scale(0.9)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "gradient-shift": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        morph: {
          "0%, 100%": { borderRadius: "60% 40% 30% 70% / 60% 30% 70% 40%" },
          "50%": { borderRadius: "30% 60% 70% 40% / 50% 60% 30% 60%" },
        },
        "text-reveal": {
          from: { opacity: "0", transform: "translateY(40px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        heartbeat: {
          "0%, 100%": { transform: "scale(1)" },
          "15%": { transform: "scale(1.15)" },
          "30%": { transform: "scale(1)" },
          "45%": { transform: "scale(1.1)" },
          "60%": { transform: "scale(1)" },
        },
        "notification-slide-in": {
          from: { transform: "translateX(100%)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "notification-slide-out": {
          from: { transform: "translateX(0)", opacity: "1" },
          to: { transform: "translateX(100%)", opacity: "0" },
        },
        "orb-move": {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "25%": { transform: "translate(30px, -50px) scale(1.1)" },
          "50%": { transform: "translate(-20px, 20px) scale(0.9)" },
          "75%": { transform: "translate(40px, 30px) scale(1.05)" },
        },
      },
      backgroundImage: {
        "gradient-spark": "linear-gradient(135deg, #ff007f 0%, #7a00cc 100%)",
        "gradient-primary": "var(--gradient-primary)",
        "gradient-warm": "var(--gradient-warm)",
        "gradient-cool": "var(--gradient-cool)",
        "gradient-aurora": "var(--gradient-aurora)",
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      boxShadow: {
        glow: "0 0 20px rgba(255, 0, 127, 0.15)",
        "glow-lg": "0 0 40px rgba(255, 0, 127, 0.25)",
        "glow-xl": "0 0 60px rgba(255, 0, 127, 0.35)",
        "glow-cyan": "0 0 20px rgba(0, 216, 255, 0.15)",
        "glow-purple": "0 0 20px rgba(122, 0, 204, 0.15)",
        "glow-pink": "var(--shadow-glow-pink)",
        "glow-lg-custom": "var(--shadow-glow-lg)",
        card: "0 4px 24px rgba(0, 0, 0, 0.2)",
        "card-lg": "0 8px 48px rgba(0, 0, 0, 0.3)",
        "card-xl": "0 16px 64px rgba(0, 0, 0, 0.4)",
        "floating": "0 8px 32px rgba(0, 0, 0, 0.3), 0 2px 8px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.06)",
        "floating-hover": "0 16px 48px rgba(0, 0, 0, 0.4), 0 4px 12px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.08)",
      },
      backdropBlur: {
        xs: "2px",
      },
      transitionTimingFunction: {
        spring: "var(--ease-spring)",
        "spring-bouncy": "var(--ease-spring-bouncy)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
        slower: "var(--duration-slower)",
        slowest: "var(--duration-slowest)",
      },
      zIndex: {
        base: "var(--z-base)",
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        fixed: "var(--z-fixed)",
        "modal-backdrop": "var(--z-modal-backdrop)",
        modal: "var(--z-modal)",
        popover: "var(--z-popover)",
        tooltip: "var(--z-tooltip)",
        toast: "var(--z-toast)",
      },
      spacing: {
        "1": "var(--space-1)",
        "2": "var(--space-2)",
        "3": "var(--space-3)",
        "4": "var(--space-4)",
        "5": "var(--space-5)",
        "6": "var(--space-6)",
        "8": "var(--space-8)",
        "10": "var(--space-10)",
        "12": "var(--space-12)",
        "16": "var(--space-16)",
        "20": "var(--space-20)",
        "24": "var(--space-24)",
      },
    },
  },
  plugins: [],
};
export default config;